Steam Boiler:
  name: 'Steam'
  control_channel: 1
  control_k1: 885
  control_k2: 2790
  control_k3: 0
  kd: 0
  ki: 0
  kp: 10
  moutput: auto
  pwm_frequency: 1
  relayduty:
    Relay1: 0
    Relay2: 0
    Relay3: 0
    Relay4: 0
    Relay5: 0
  relaypin:
    Relay1: 0
    Relay2: 0
    Relay3: 0
    Relay4: 0
    Relay5: 0
  safety_channel: 2
  safety_k1: 885
  safety_k2: 2790
  safety_k3: 0
  safety_mode: 'off'
  safety_value: 0
  setpoint:
    '2016-08-12 09:00:00': 30
    '2016-08-13 09:00:00': 35
    '2016-08-14 09:00:00': 40
  sleeptime: 5
  ssrduty: 4
  ssrmode: pwm
  ssrpin: 22
  terminate: 0
  umax: 100
  umin: 0
  Temperature: 90
  Setpoint: 92

Buzzer:
  frequency: 2000
  duty: 50
  duration: 0
  pin: 27
  terminate: 1
  Temperature: 0

Fermenter1:
  Temperature: 17
  Setpoint: 17

Fermenter2:
  Temperature: 120
  Setpoint: 18

Fermenter3:
  Temperature: 18
  Setpoint: 19