Buzzer: {duration: 0, duty: 50, frequency: 2000, pin: 27, terminate: 'False'}
Steam Boiler:
  Delete_This_Process: 'False'
  autotune_convergence: 0.01
  autotune_gainsign: 1
  autotune_hysteresis: 1.0
  autotune_maxiterations: 20.0
  autotune_on: 'False'
  autotune_sleeptime: 0.1
  autotune_temp: 102.0
  control_channel: 1.0
  control_k1: 0.0
  control_k2: 3138.413
  control_k3: -3.10125
  kd: 0.0
  ki: 0.157
  kp: 4.384
  moutput: auto
  pwm_frequency: 1.0
  relayduty: {Relay1: 0.0, Relay2: 0.0, Relay3: 0.0, Relay4: 0.0, Relay5: 0.0}
  relaypin: {Relay1: 'off', Relay2: 'off', Relay3: 'off', Relay4: 'off', Relay5: 'off'}
  safety_channel: 2.0
  safety_k1: 885.0
  safety_k2: 2790.0
  safety_k3: 0.0
  safety_mode: 'off'
  safety_value: 0.0
  setpoint: {'2016-08-12 09:00:00': 30.0, '2017-08-14 09:00:00': 40.0}
  sleeptime: 2.0
  ssrduty: 4.0
  ssrmode: pwm
  ssrpin: 14.0
  terminate: 'False'
  umax: 100.0
  umin: 0.0
